version: '3'
services:
  db:
    image: postgres:10.14
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  server:
    build: .
    tty: true
    volumes:
      - .:/myapp
    working_dir: /myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    # command: bash
    command: > 
      bash -c "rm -f tmp/pids/server.pid &&
          bundle exec rails s -p 3000 -b '0.0.0.0'"